#!/bin/csh

# TRAIN ON ONLY THE PREDICTION LOSS

foreach x ( 50 100 200 400 800 ) 
   foreach s (5) # iterations
      python rnn_attr.py -task reber -seq_len 20 -display_epoch 50 -training_epochs 2500 -n_replications 100 -lrate_prediction .002 -lrate_attractor .0 -arch tanh -latent_attractor_space -n_hidden 20 -n_attractor_hidden 40 -loss_switch_frequency 0 -report_best_train_performance -batch_size $x -noise_level .250 -n_attractor_steps $s -n_train $x -train_attr_weights_on_prediction -loss_switch_freq 0 -attr_loss_start 0 > rnna_${x}_20hid_${s}iter.out
   end
end
