#!/bin/csh

# NO ATTRACTOR NET
# FIXED 500 epochs

foreach x ( 400 800 ) # 50 100 200 )
   python rnn_attr.py -task reber -display_epoch 50 -training_epochs 2500 -n_replications 100 -lrate_prediction .002 -arch tanh -latent_attractor_space -n_hidden 20 -n_attractor_hidden 40 -loss_switch_frequency 0 -report_best_train_performance -batch_size $x -noise_level .250 -lrate_attractor .000 -n_attractor_steps 0 -n_train $x -seq_len 20 > rnn_${x}_20hid.out
end

