#!/bin/csh

# TRAIN ATTRACTOR NET ONLY ON PREDICTION TASK

foreach x ( 10 15 20 25 30  )
   python rnn_attr.py -seq_len $x -task majority -display_epoch 100 -training_epochs 2500 -n_replications 100 -lrate_prediction .002 -n_attractor_steps 5 -arch tanh -latent_attractor_space -n_hidden 10 -n_attractor_hidden 20 -input_noise_level 0.15 -loss_switch_frequency 0 -report_best_train_performance -batch_size 256 -noise_level .250 -lrate_attractor .000 -train_attr_weights_on_prediction > rnna_${x}_5step_10hid.out
end
